[package]
name    = "enso-automata"
version = "0.1.1"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]

[dependencies]
enso-prelude = { version = "0.1.1", path = "../prelude" }
